image: registry.gitlab.com/christiantragesser/dind-py:latest

variables:
    DOCKER_DRIVER: overlay2
    LOCAL_TAG: local/yadi
    EXT_TAG: $CI_REGISTRY/christiantragesser/yadi
    VERSIONS:
      - latest
      - $CI_COMMIT_SHA
    
services:
- docker:stable-dind

stages:
  - test

test:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - $CI_PROJECT_DIR/ci.py test
    - $CI_PROJECT_DIR/ci.py scan
    - for i in $VERSIONS; do docker tag $LOCAL_TAG ${EXT_TAG}:$i; done 
    - for i in $VERSIONS; do docker push ${EXT_TAG}:$i | grep -e "The push refers to" -e latest; done 
  only:
    - master
  artifacts:
    paths:
    - "*.cve-scan.json"
    expire_in: 1 week